scriptpath='calculator.pyw'
scriptname="Python calculator"
scriptdesc="Basic python calculator"
scriptver="1.0"
scripticon="icon.ico"
scriptauthor="Mike Guilmot"
scriptcopyright="FreeWare"
#scriptextraincludes=(".",["file.txt","file2.txt"])
scriptextraincludes=(".",["README.txt","LICENSE.txt"])
scriptpackages=[]
